projects:
  AuthApi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: 4wfp4ywg4jfv5p7pzpbfvyhoaa
      endpoints:
        prod: >-
          https://tggqvtymyvhpnpdxev6lxyhndq.appsync-api.us-east-1.amazonaws.com/graphql
